#!/bin/sh
USER=rholl
HOST=plexserver             
DIR=/public_html/   # the directory where your web site files should go

rm -rf Public/
hugo && rsync -avz --delete Public/ ${USER}@${HOST}:~/${DIR}

exit 0
